### ISSUE TITLE
Threading issues with RenderingTypeResolver.ResolveCreator

### ISSUE THREAD

**Issue by bmcdavid** [bmcdavid/Renderings#2]
Duplicate key dictionary issue.
```System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Renderings.RenderingTypeResolver.ResolveCreator[TSource](String alias)
   at Renderings.RenderingCreatorScoped.GetCreator[T](String alias)
   at UmbracoCloudTrial.Core.Models.ViewModels.PageViewModelBase.```

**Comment by bmcdavid** [comment]
Fixed in 1.0.1
